/***** DO NOT EDIT THIS FILE *****/
// hellomonkey.js generated by MonkeyTalk at 2013-02-06 15:25:31 ICT

load("libs/MonkeyTalkAPI.js");


var hellomonkey = {};

/*** script -- HappyHotelSearch ***/
hellomonkey.HappyHotelSearch = function(app) {
	MT.Script.call(this, app, "HappyHotelSearch.mt");
};

hellomonkey.HappyHotelSearch.prototype = new MT.Script;

hellomonkey.HappyHotelSearch.prototype.call = function(destonationName, currencyISO) {
	//run: HappyHotelSearch.mt
	MT.Script.prototype.call(this, destonationName, currencyISO);
};

MT.Application.prototype.happyHotelSearch = function() {
	return new hellomonkey.HappyHotelSearch(this);
};

/*** script -- firstTry ***/
hellomonkey.firstTry = function(app) {
	MT.Script.call(this, app, "firstTry.mt");
};

hellomonkey.firstTry.prototype = new MT.Script;

hellomonkey.firstTry.prototype.call = function(errorText) {
	//run: firstTry.mt
	MT.Script.prototype.call(this, errorText);
};

MT.Application.prototype.firstTry = function() {
	return new hellomonkey.firstTry(this);
};

/*** script -- getBackToTheStart ***/
hellomonkey.getBackToTheStart = function(app) {
	MT.Script.call(this, app, "getBackToTheStart.mt");
};

hellomonkey.getBackToTheStart.prototype = new MT.Script;

hellomonkey.getBackToTheStart.prototype.call = function(stepBack) {
	//run: getBackToTheStart.mt
	MT.Script.prototype.call(this, stepBack);
};

MT.Application.prototype.getBackToTheStart = function() {
	return new hellomonkey.getBackToTheStart(this);
};

/*** script -- init1 ***/
hellomonkey.init1 = function(app) {
	MT.Script.call(this, app, "init1.mt");
};

hellomonkey.init1.prototype = new MT.Script;

hellomonkey.init1.prototype.call = function() {
	//run: init1.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.init1 = function() {
	return new hellomonkey.init1(this);
};

/*** script -- regionNotFound ***/
hellomonkey.regionNotFound = function(app) {
	MT.Script.call(this, app, "regionNotFound.mt");
};

hellomonkey.regionNotFound.prototype = new MT.Script;

hellomonkey.regionNotFound.prototype.call = function(errorText) {
	//run: regionNotFound.mt
	MT.Script.prototype.call(this, errorText);
};

MT.Application.prototype.regionNotFound = function() {
	return new hellomonkey.regionNotFound(this);
};

