/***** DO NOT EDIT THIS FILE *****/
// hellomonkey.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var hellomonkey = {};

/*** script -- HappyHotelSearch ***/
hellomonkey.HappyHotelSearch = function(app) {
	MT.Script.call(this, app, "HappyHotelSearch.mt");
};

hellomonkey.HappyHotelSearch.prototype = new MT.Script;

hellomonkey.HappyHotelSearch.prototype.call = function(destonationName, currencyISO) {
	//run: HappyHotelSearch.mt
	MT.Script.prototype.call(this, destonationName, currencyISO);
};

MT.Application.prototype.happyHotelSearch = function() {
	return new hellomonkey.HappyHotelSearch(this);
};

/*** script -- HappyHotelSearchMod ***/
hellomonkey.HappyHotelSearchMod = function(app) {
	MT.Script.call(this, app, "HappyHotelSearchMod.mt");
};

hellomonkey.HappyHotelSearchMod.prototype = new MT.Script;

hellomonkey.HappyHotelSearchMod.prototype.call = function(destonationName, currencyISO) {
	//run: HappyHotelSearchMod.mt
	MT.Script.prototype.call(this, destonationName, currencyISO);
};

MT.Application.prototype.happyHotelSearchMod = function() {
	return new hellomonkey.HappyHotelSearchMod(this);
};

/*** script -- changeGuestsHigh ***/
hellomonkey.changeGuestsHigh = function(app) {
	MT.Script.call(this, app, "changeGuestsHigh.mt");
};

hellomonkey.changeGuestsHigh.prototype = new MT.Script;

hellomonkey.changeGuestsHigh.prototype.call = function() {
	//run: changeGuestsHigh.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.changeGuestsHigh = function() {
	return new hellomonkey.changeGuestsHigh(this);
};

/*** script -- changingGuestNumber ***/
hellomonkey.changingGuestNumber = function(app) {
	MT.Script.call(this, app, "changingGuestNumber.mt");
};

hellomonkey.changingGuestNumber.prototype = new MT.Script;

hellomonkey.changingGuestNumber.prototype.call = function(noAdult, noChild) {
	//run: changingGuestNumber.mt
	MT.Script.prototype.call(this, noAdult, noChild);
};

MT.Application.prototype.changingGuestNumber = function() {
	return new hellomonkey.changingGuestNumber(this);
};

/*** script -- firstTry ***/
hellomonkey.firstTry = function(app) {
	MT.Script.call(this, app, "firstTry.mt");
};

hellomonkey.firstTry.prototype = new MT.Script;

hellomonkey.firstTry.prototype.call = function(errorText) {
	//run: firstTry.mt
	MT.Script.prototype.call(this, errorText);
};

MT.Application.prototype.firstTry = function() {
	return new hellomonkey.firstTry(this);
};

/*** script -- getBackToTheStart ***/
hellomonkey.getBackToTheStart = function(app) {
	MT.Script.call(this, app, "getBackToTheStart.mt");
};

hellomonkey.getBackToTheStart.prototype = new MT.Script;

hellomonkey.getBackToTheStart.prototype.call = function(stepBack) {
	//run: getBackToTheStart.mt
	MT.Script.prototype.call(this, stepBack);
};

MT.Application.prototype.getBackToTheStart = function() {
	return new hellomonkey.getBackToTheStart(this);
};

/*** script -- init1 ***/
hellomonkey.init1 = function(app) {
	MT.Script.call(this, app, "init1.mt");
};

hellomonkey.init1.prototype = new MT.Script;

hellomonkey.init1.prototype.call = function() {
	//run: init1.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.init1 = function() {
	return new hellomonkey.init1(this);
};

/*** script -- regionNotFound ***/
hellomonkey.regionNotFound = function(app) {
	MT.Script.call(this, app, "regionNotFound.mt");
};

hellomonkey.regionNotFound.prototype = new MT.Script;

hellomonkey.regionNotFound.prototype.call = function(errorText) {
	//run: regionNotFound.mt
	MT.Script.prototype.call(this, errorText);
};

MT.Application.prototype.regionNotFound = function() {
	return new hellomonkey.regionNotFound(this);
};

